### ISSUE TITLE
minecraft bug crash

### ISSUE THREAD

**Issue by Lolothepro** [microsoft/openjdk#135]
Ubuntu

Openjdk 16.0.1 2021-04-20
OpenJDK Runtime Environment Microsoft-22300 (build 16.0.1+9)
OpenJDK 64-Bit Server VM Microsoft-22300 (build 16.0.1+9, mixed mode)

Start Minecraft

Logs is in attached file

[hs_err_pid12238.log](https://github.com/microsoft/openjdk/files/7269293/hs_err_pid12238.log)

I've not more information

**Comment by brianjstafford** [comment]
Hi @Lolothepro! This looks like an LWJGL bug. Can you please submit this issue over at https://bugs.mojang.com/projects/MC/issues/? The Mojang team will take the first look. Thanks!

**Comment by Marcono1234** [comment]
They have reported it as [MC-237569](https://bugs.mojang.com/browse/MC-237569) (private report), but with different non LWJGL-related?) JVM crashes attached.

**Comment by Lolothepro** [comment]
So I guess I have to wait for the bug to be fixed, right?
any idea how long before Mojang fixes the bug?

**Comment by Marcono1234** [comment]
It is difficult to tell when the developers will fix this bug due to the large number of bug reports.
Could you please in the meantime try [updating your graphics card drivers](https://help.minecraft.net/hc/en-us/articles/4409137348877-Minecraft-Java-Edition-Game-Crashes-and-Performance-Issues-FAQ#h_01FFNR5S1APTFHGR9K2W3JANZ4) and let us know if that helped.

In case that does not help you can also try contacting [Community Support](https://discord.gg/58Sxm23).
