### ISSUE TITLE
`JAVA_HOME` not set by MSI installer

### ISSUE THREAD

**Issue by camilo-s** [microsoft/openjdk#397]
**Describe the bug**
When silently installed installing OpenJDK via MSI package as described in the documentation, installation goes through normally but`JAVA_HOME` doesn't get set and the `PATH` variable doesn't get updated accordingly

**Desktop (please complete the following information):**

```
[System.Environment]::OSVersion.Version
Major  Minor  Build  Revision
-----  -----  -----  --------
10     0      20348  0       
```

**MSFT Build of OpenJDK Version:**

Microsoft Build of OpenJDK with Hotspot 17.0.5+8 (x64)

**To Reproduce:**

Follow the installation instructions described [here](https://learn.microsoft.com/en-us/java/openjdk/install#install-via-msi)

**Expected behavior**
The MSFT build of OpenJDK gets installed, `JAVA_HOME` and `PATH` variables get configured as per the `FeatureJavaHome` switch. 

**Screenshots, Logs etc**
No error is displayed.

**Additional context**
A previous silent automatic installation of Microsoft Build of OpenJDK with Hotspot 17.0.3+7 (x64) on Windows 10.0.17763 went through as expected, with correct configuration of the `JAVA_HOME` and `PATH` variables.

**Comment by d3r3kk** [comment]
Thanks for reporting!

We have some updates coming for our installer in the next PSU release in April 2023. We will ensure we investigate this and update the installers as necessary to correct the behaviour. (This is going to be fixed along with the update that is already corrected upstream and will be shipped in April as well, see #344).

**Comment by wendiedang** [comment]
@d3r3kk The issue was not reproduced on JDK17.0.6 & JDK11.0.18. The detailed results are as below:
<html xmlns:v="urn:schemas-microsoft-com:vml"
xmlns:o="urn:schemas-microsoft-com:office:office"
xmlns:x="urn:schemas-microsoft-com:office:excel"
xmlns="http://www.w3.org/TR/REC-html40">

<head>

<meta name=ProgId content=Excel.Sheet>
<meta name=Generator content="Microsoft Excel 15">
<link id=Main-File rel=Main-File
href="file:///C:/Users/V-WEND~1/AppData/Local/Temp/msohtmlclip1/01/clip.htm">
<link rel=File-List
href="file:///C:/Users/V-WEND~1/AppData/Local/Temp/msohtmlclip1/01/clip_filelist.xml">
<style>

</style>
</head>

<body link="#0563C1" vlink="#954F72">



Platform | Binary | Results
-- | -- | --
Window x64 | jdk11.0.18 (7208460) | Not   repro
Window x64 | 17.0.6+10 (7209853) | Not   repro
windows   aarch64 | 11.0.18+10(7208460) | Not   repro
windows   aarch64 | 17.0.6+10 (7209853) | Not   repro



</body>

</html>

**Comment by karianna** [comment]
@camilo-s Can you try with our 17.0.6 installer?

**Comment by wendiedang** [comment]
@d3r3kk Verified the issue by using JDK11.0.18+10 & JDK17.0.6+10, the JAVA_HOME and PATH variable both get updated correctly.
**JDK17.0.6+10:
 clean install (no jdk installed in the machine):**
![17 0 6+10_clean_install](https://user-images.githubusercontent.com/104541810/218410021-016a47af-a1f1-4fc7-9d58-81f281c0dc71.png)
 **The previous version of JDK(such as: JDK17.0.3) has installed on the machine, and then installed JDK17.0.6+10, the JAVA_HOME and PATH variable also get updated correctly.**
![17 0 6+10](https://user-images.githubusercontent.com/104541810/218410609-75f501b5-0d17-4d60-aa26-43d41674198a.png)

**Comment by d3r3kk** [comment]
Thank you @wendiedang, for that level of detail.

@camilo-s we feel that there is no concern based on the findings above. Please add to the thread if you have further concerns not covered by the testing we've done.

**Comment by d3r3kk** [comment]
Closing, feel free to reopen if you are still finding issues @camilo-s.
