### ISSUE TITLE
Hi i have this problem that i tried every thing but nothing changes anyone can help? 

### ISSUE THREAD

**Issue by HassanMC123** [microsoft/openjdk#408]
```
#
# A fatal error has been detected by the Java Runtime Environment:
#
#  EXCEPTION_ACCESS_VIOLATION (0xc0000005) at pc=0x00007ffca98471d9, pid=17920, tid=10252
#
# JRE version: OpenJDK Runtime Environment Microsoft-32931 (17.0.3+7) (build 17.0.3+7-LTS)
# Java VM: OpenJDK 64-Bit Server VM Microsoft-32931 (17.0.3+7-LTS, mixed mode, tiered, compressed oops, compressed class ptrs, g1 gc, windows-amd64)
# Problematic frame:
# V  [jvm.dll+0x3071d9]
#
# No core dump will be written. Minidumps are not enabled by default on client versions of Windows
#
# If you would like to submit a bug report, please visit:
#   https://github.com/microsoft/openjdk/issues
#
```

**Comment by karianna** [comment]
@HassanMC123 Can you please try our latest 17.0.6 build and let us know if that is fixed?

**Comment by brunoborges** [comment]
Possibly Minecraft?

**Comment by karianna** [comment]
Likely as 17.0.3 was shipped with 1.19.2

**Comment by Div3r002** [comment]
Hi, I have the exact same problem on minecraft, did you already find a solution?

**Comment by pigster117** [comment]
I have the same issue, no clue how to fix it.

**Comment by karianna** [comment]
Hi all, 

Thank you for the report!
Please submit this issue over at the [Mojang bug tracker](https://bugs.mojang.com/projects/MC/summary). Please search for existing reports first; in case you do not find any, create a new report and let us know about the issue number here (e.g. `MC-123456`). The Mojang team will take the first look. If an OpenJDK bug is identified, the Mojang team will contact the Microsoft Build of OpenJDK team to address the issue.

-----

Some more context:

99% of Minecraft crashes we see are caused due to a mod or needing to upgrade graphics drivers to their latest versions.  This is because Minecraft Java uses the LWJGL library which in turn calls native operating system components for the graphical rendering etc. An error is reported in a Java crash log (like the above above example) since the Java process launches the game (and so the error propagates back to Java, but the original meaning is often lost).

Our recommend mitigation steps are:

* Make sure you are using the official launcher
* Remove any mods and see if the game is stable.  If so, report the crash to the mod author
* Upgrade Graphics drivers to their latest version
* You can also try to upgrade the underlying Java to 17.0.6 (in the advanced settings of the launcher) but this typically won't be a fix.
