### ISSUE TITLE
Any version above 1.19 crashes instantly

### ISSUE THREAD

**Issue by LenoraFX** [microsoft/openjdk#425]
**Describe the bug**
I cannot start any minecraft versions above 1.19, whenever i try to start any versions above 1.19 it gives exit code 1 and these reports

**Desktop (please complete the following information):**

OS & version [e.g. Windows 10, 1822]: Windows 10

**MSFT Build of OpenJDK Version:**
java version "1.8.0_361"
Java(TM) SE Runtime Environment (build 1.8.0_361-b09)
Java HotSpot(TM) 64-Bit Server VM (build 25.361-b09, mixed mode)

**To Reproduce:**

1. Go to 'Minecraft Launher'
2. Choose version 1.19.2
3. Click Play
4. And it crashes as soon as i see the 1.19.2 window and gives this error

**Expected behavior**
I expected the game to start normaly

**Sc
[hs_err_pid2976.log](https://github.com/microsoft/openjdk/files/11249594/hs_err_pid2976.log)
[latest.log](https://github.com/microsoft/openjdk/files/11249595/latest.log)
reens

**Additional context**

**Comment by LenoraFX** [comment]
It didn't worked, my drivers are the latest, I'm not using any mods if u know how to read the crash report then u'd know that im using the vanilla minecraft 1.19.2 and its THE OFFICAL launcher

**Comment by brunoborges** [comment]
Hi @LenoraFX, 

If you are still experiencing the crash with the official launcher and without any mods installed, please submit this issue over at the [Mojang bug tracker](https://bugs.mojang.com/projects/MC/summary).

Once Mojang confirms the issue is with our OpenJDK runtime (instead of with any of the Minecraft components), then we will certainly take action.

Thanks,
Bruno
