### ISSUE TITLE
crashing when going through portals or tp

### ISSUE THREAD

**Issue by KRIPOMC** [microsoft/openjdk#435]
**Describe the bug**
when going though a portal my game crash
**Desktop (please complete the following information):**

OS & version [e.g. Windows 10, 1822]:
windows 10
**MSFT Build of OpenJDK Version:**
1.19.4
The output from `java --version`

**To Reproduce:**

**Expected behavior**
not crashing when going though portal
**Screenshots, Logs etc**
If applicable, add screenshots, logs to help explain your problem.
https://justpaste.it/d0ncd heres the crash report
**Additional context**

**Comment by karianna** [comment]
Thank you for the report!
It looks like you are using a modified version of Minecraft. The following was detected in your crash report:
```
--launchTarget forgeclient
--fml.forgeVersion
```
Please try the following:
- Update your graphics drivers, see [this Minecraft Help Center article](https://help.minecraft.net/hc/en-us/articles/4409137348877-Minecraft-Java-Edition-Game-Crashes-and-Performance-Issues-FAQ), section "Update your Video Card Drivers";
  often Minecraft crashes are caused by outdated graphics drivers
- Try disabling the mods you have installed one by one until you find the mod causing the crash, then report the crash to the mod author
- If you are using a third-party launcher, try the [official launcher](https://www.minecraft.net/download) instead

If none of the above helped, and you are still experiencing the crash with the official launcher and without any mods installed, please submit this issue over at the [Mojang bug tracker](https://bugs.mojang.com/projects/MC/summary). Please search for existing reports first; in case you do not find any, create a new report and let us know about the issue number here (e.g. `MC-123456`).
The Mojang team will take the first look. If an OpenJDK bug is identified, the Mojang team will contact the Microsoft Build of OpenJDK team to address the issue.
