### ISSUE TITLE
A fatal error has been detected by the Java Runtime Environment: # #  EXCEPTION_ACCESS_VIOLATION (0xc0000005) at pc=0x00007ffe299b2b60, pid=4404, tid=10600 # # JRE version: OpenJDK Runtime Environment Microsoft-32931 (17.0.3+7) (build 17.0.3+7-LTS) # Java VM: OpenJDK 64-Bit Server VM Microsoft-32931 (17.0.3+7-LTS, mixed mode, tiered, compressed oops, compressed class ptrs, g1 gc, windows-amd64) # Problematic frame: # C  [atio6axx.dll+0x192b60] # # No core dump will be written. Minidumps are not enabled by default on client versions of Windows # # If you would like to submit a bug report, please visit: #   https://github.com/microsoft/openjdk/issues # The crash happened outside the Java Virtual Machine in native code. # See problematic frame for where to report the bug.

### ISSUE THREAD

**Issue by alien0828** [microsoft/openjdk#442]
**Describe the bug**

**Desktop (please complete the following information):**

OS & version [e.g. Windows 10, 1822]:

**MSFT Build of OpenJDK Version:**

The output from `java --version`

**To Reproduce:**

**Expected behavior**

**Screenshots, Logs etc**
If applicable, add screenshots, logs to help explain your problem.

**Additional context**

**Comment by karianna** [comment]
Thank you for the report!
It looks like you are using a modified version of Minecraft. The following was detected in your crash report:
```
--launchTarget forgeclient
--fml.forgeVersion
```
Please try the following:
- Update your graphics drivers, see [this Minecraft Help Center article](https://help.minecraft.net/hc/en-us/articles/4409137348877-Minecraft-Java-Edition-Game-Crashes-and-Performance-Issues-FAQ), section "Update your Video Card Drivers";
  often Minecraft crashes are caused by outdated graphics drivers
- Try disabling the mods you have installed one by one until you find the mod causing the crash, then report the crash to the mod author
- If you are using a third-party launcher, try the [official launcher](https://www.minecraft.net/download) instead

If none of the above helped, and you are still experiencing the crash with the official launcher and without any mods installed, please submit this issue over at the [Mojang bug tracker](https://bugs.mojang.com/projects/MC/summary). Please search for existing reports first; in case you do not find any, create a new report and let us know about the issue number here (e.g. `MC-123456`).
The Mojang team will take the first look. If an OpenJDK bug is identified, the Mojang team will contact the Microsoft Build of OpenJDK team to address the issue.
