### ISSUE TITLE
Obnoxious random crash

### ISSUE THREAD

**Issue by FooterMan15** [microsoft/openjdk#452]
**Describe the bug**
When running Modded MC, the game randomly produces a crash, along with a hs_err_pid.log.
Info:
MC 1.19.2
Forge 43.2.8
Modpack in use - https://github.com/TheGangModpacks/Fun-in-the-Sky
Graphics driver - 531.79 (Latest available)

**Desktop (please complete the following information):**
Windows 11
Build - 22621.1702

**MSFT Build of OpenJDK Version:**
11.0.16.1 2022-08-12 LTS

**To Reproduce:**
Run MC, potentially while running the Modded pack posted above ^.
Load into a world.
Wait for random crash.

**Expected behavior**
No crash?

**Screenshots, Logs etc**
[MC Latest.log (Includes OpenGL errors)](https://gist.github.com/FooterMan15/e86a864d89325cf749c8605be2c0c2af)
[hs_err_pid](https://gist.github.com/FooterMan15/2da39bd5241e412361de42dafbcc8db0)

**Additional context**
Does not happen when performing an action (eg, moving, punching).

**Comment by brunoborges** [comment]
Thank you for the report!
It looks like you are using a modified version of Minecraft. The following was detected in your crash report:
```
--launchTarget forgeclient
--fml.forgeVersion
```
Please try the following:
- Update your graphics drivers, see [this Minecraft Help Center article](https://help.minecraft.net/hc/en-us/articles/4409137348877-Minecraft-Java-Edition-Game-Crashes-and-Performance-Issues-FAQ), section "Update your Video Card Drivers";
  often Minecraft crashes are caused by outdated graphics drivers
- Try disabling the mods you have installed one by one until you find the mod causing the crash, then report the crash to the mod author
- If you are using a third-party launcher, try the [official launcher](https://www.minecraft.net/download) instead

If none of the above helped, and you are still experiencing the crash with the official launcher and without any mods installed, please submit this issue over at the [Mojang bug tracker](https://bugs.mojang.com/projects/MC/summary). Please search for existing reports first; in case you do not find any, create a new report and let us know about the issue number here (e.g. `MC-123456`).
The Mojang team will take the first look. If an OpenJDK bug is identified, the Mojang team will contact the Microsoft Build of OpenJDK team to address the issue.

**Comment by FooterMan15** [comment]
Apologies, but I can't accept that. I've been having the same issue on 5 other modpacks. I think it's caused by a Java update.

**Comment by brunoborges** [comment]
@FooterMan15, appreciate your frustration, but please contact the modpack author. We Microsoft do not certify (which means we do not test them) nor provide support for Minecraft mods.

**Comment by FooterMan15** [comment]
I am the modpack author. I have tried several other packs made by others. Unfortunately I get the same result.

That being said, I understand you have nothing to do with mods. The error log said to report it here, so I did. If you confirm it's not MS's fault, I'll try some other things.

**Comment by brunoborges** [comment]
If you can confirm your mod works with a JDK from a different vendor, but of exact same version, let us know. 

But that is correct, Microsoft only provide support for Minecraft Java Edition. Not for mods.

**Comment by FooterMan15** [comment]
Hiya, I'm back.
I tried two JDK vendors, and it seems the one I grabbed from Adoptium [here](https://adoptium.net/temurin/releases/) works perfectly. However, the version from Oracle [here](https://www.oracle.com/java/technologies/downloads/) gives that original crash up in the thread ^^ and might also have a memory leak or something, because I also consistently get "Out of Memory" errors.
Apologies if this isn't much help, but I'm happy now with the Adoptium version.
