### ISSUE TITLE
Label "Reported Upstream" applied because of quoted "MC-123456"

### ISSUE THREAD

**Issue by KalleOlaviNiemitalo** [microsoft/openjdk#472]
**Describe the bug**

GitHub workflow `minecraft-crash-reported-upstream-check.yml` added the "Reported Upstream" label because the reporter replied by email and quoted the instructions that include the sample `MC-123456` issue key.

**Expected behavior**

The workflow should ignore the `MC-123456` in the quoted text.

**Screenshots, Logs etc**

<https://github.com/microsoft/openjdk/issues/451#issuecomment-1586311539>

> Please search for existing reports first; in case you do not find any, create a new report and let us know about the issue number here (e.g. MC-123456).

**Comment by Marcono1234** [comment]
At least this shows that the action is working..., though it is quite unfortunate that apparently so far no reporter seems to have commented with a real Mojira issue key yet.

@KalleOlaviNiemitalo, I tested the fix you proposed above in my fork and it seems to work as expected; `MC-123456` is ignored whereas `MC-1234567` is detected.
Maybe the comment could be made a bit more generic by omitting "in email" because this can also triggered by any mention of that sample issue key, as seen by your commit above.

Are you planning to submit a pull request for this fix? (though that might require a CLA to be signed; not sure how strict the maintainers here see this for such a small change)

**Comment by Marcono1234** [comment]
Ok, do you allow me then to submit a pull request with your proposed fix?

**Comment by karianna** [comment]
@Marcono1234 we'd appreciate it!
