### ISSUE TITLE
i cannot launch Curseforge Mods/Modpacks without removing the JVM Arguments Thing

### ISSUE THREAD

**Issue by gamermc3454** [microsoft/openjdk#484]
**Describe the bug**
it isnt letting me play any sort of mod/modpack on Curseforge App/installer, so far only one pack has worked without me removing the JVM Arguements.

**Desktop (please complete the following information):**

OS & version [Windows 11, OS: 22621.1848]:

**MSFT Build of OpenJDK Version:**

The output from `java --version`

**To Reproduce:**

1. Go to 'Curseforge'
2. Click on 'start (dont remove arguements)'
3. Scroll down on 'Console'

**Expected behavior**
Curseforge Mod/Modpacks are ment to start

**Screenshots, Logs etc**
If applicable, add screenshots, logs to help explain your problem.

**Additional context**
![Screenshot 2023-06-23 121240](https://github.com/microsoft/openjdk/assets/100799011/944aea21-330b-4ba5-acd8-a0a8558e48a7)

**Comment by karianna** [comment]
Thank you for the report!
It looks like you are reporting that the game Minecraft crashed for you. Please try the following:
- Update your graphics drivers, see [this Minecraft Help Center article](https://help.minecraft.net/hc/en-us/articles/4409137348877-Minecraft-Java-Edition-Game-Crashes-and-Performance-Issues-FAQ), section "Update your Video Card Drivers";
  often Minecraft crashes are caused by outdated graphics drivers
- In case you are using mods, try disabling them one by one until you find the mod causing the crash, then report the crash to the mod author
- If you are using a third-party launcher, try the [official launcher](https://www.minecraft.net/download) instead

If none of the above helped, and you are still experiencing the crash with the official launcher and without any mods installed, please submit this issue over at the [Mojang bug tracker](https://bugs.mojang.com/projects/MC/summary). Please search for existing reports first; in case you do not find any, create a new report and let us know about the issue number here (e.g. `MC-123456`).
The Mojang team will take the first look. If an OpenJDK bug is identified, the Mojang team will contact the Microsoft Build of OpenJDK team to address the issue.

**Comment by gamermc3454** [comment]
Hello Martijn, thank you for the response. And I am the Mod Author testing my own brand new Minecraft mod. I will try updating my video card drivers now thank you Sent from Mail for Windows From: Martijn VerburgSent: Saturday, June 24, 2023 1:09 AMTo: microsoft/openjdkCc: gamermc3454; AuthorSubject: Re: [microsoft/openjdk] i cannot launch Curseforge Mods/Modpacks without removing the JVM Arguments Thing (Issue #484) Thank you for the report!It looks like you are reporting that the game Minecraft crashed for you. Please try the following:Update your graphics drivers, see this Minecraft Help Center article, section "Update your Video Card Drivers";often Minecraft crashes are caused by outdated graphics driversIn case you are using mods, try disabling them one by one until you find the mod causing the crash, then report the crash to the mod authorIf you are using a third-party launcher, try the official launcher insteadIf none of the above helped, and you are still experiencing the crash with the official launcher and without any mods installed, please submit this issue over at the Mojang bug tracker. Please search for existing reports first; in case you do not find any, create a new report and let us know about the issue number here (e.g. MC-123456).The Mojang team will take the first look. If an OpenJDK bug is identified, the Mojang team will contact the Microsoft Build of OpenJDK team to address the issue.—Reply to this email directly, view it on GitHub, or unsubscribe.You are receiving this because you authored the thread.Message ID: ***@***.***>
