### ISSUE TITLE
1.20.1 forge crashed help idk what to do

### ISSUE THREAD

**Issue by SteamTheBeam** [microsoft/openjdk#490]
![Screenshot 2023-06-28 090556](https://github.com/microsoft/openjdk/assets/137966142/a3a02507-7746-4276-838e-f65fc2a6e47e)

**Describe the bug**
Crashes every time I open but any mc like fabric works
keeps giving the same thing on the screen shot on top I have no mods installed
Im new to Minecraft and want to test out mods  if this comment didnt help you, I understand my problem feels like nonsense I get it, bc I dont know what to do Im just seeking for help and dont know

if possible can you try to guide me what should i provide you

**Comment by karianna** [comment]
Thank you for the report!
It looks like you are using a modified version of Minecraft. The following was detected in your crash report:
Please try the following:
- Update your graphics drivers, see [this Minecraft Help Center article](https://help.minecraft.net/hc/en-us/articles/4409137348877-Minecraft-Java-Edition-Game-Crashes-and-Performance-Issues-FAQ), section "Update your Video Card Drivers";
  often Minecraft crashes are caused by outdated graphics drivers
- Try disabling the mods you have installed one by one until you find the mod causing the crash, then report the crash to the mod author
- If you are using a third-party launcher, try the [official launcher](https://www.minecraft.net/download) instead

If none of the above helped, and you are still experiencing the crash with the official launcher and without any mods installed, please submit this issue over at the [Mojang bug tracker](https://bugs.mojang.com/projects/MC/summary). Please search for existing reports first; in case you do not find any, create a new report and let us know about the issue number here (e.g. `MC-123456`).
The Mojang team will take the first look. If an OpenJDK bug is identified, the Mojang team will contact the Microsoft Build of OpenJDK team to address the issue.
