### ISSUE TITLE
Minecraft crashing

### ISSUE THREAD

**Issue by KinFireRain** [microsoft/openjdk#68]
I've uninstalled, repaired, installed minecraft many times. Update Java, drivers etc.
Turned off my firewall. Changed the amount of RAM used. 
I've been all over the forums. Microsoft says it's not a bug but can't help me.
It says preparing, updating, then finalizing. 
As soon as it says finalizing, the screen disappears and comes back saying it crashed with the crash report.
Here is the the first part of the crash report:
 A fatal error has been detected by the Java Runtime Environment:
#
#  EXCEPTION_ACCESS_VIOLATION (0xc0000005) at pc=0x0000000000000000, pid=8120, tid=13820
#
# JRE version: OpenJDK Runtime Environment Microsoft-22300 (16.0.1+9) (build 16.0.1+9)
# Java VM: OpenJDK 64-Bit Server VM Microsoft-22300 (16.0.1+9, mixed mode, tiered, compressed oops, compressed class ptrs, g1 gc, windows-amd64)
# Problematic frame:
# C  0x0000000000000000
#
# No core dump will be written. Minidumps are not enabled by default on client versions of Windows
#
# If you would like to submit a bug report, please visit:
#   https://github.com/microsoft/openjdk/issues
# The crash happened outside the Java Virtual Machine in native code.
# See problematic frame for where to report the bug.

*****Notice it says to report the bug here!! Yet I see others with the similar problem and you told them to go to Microsoft
![Minecraft crashing 2021-06-15](https://user-images.githubusercontent.com/85905523/122131867-d6df8d80-ce07-11eb-87b3-831d6516cc99.png)

**Comment by KinFireRain** [comment]
I did. I've seen others with similar issues. One of the answers was it's not a bug.Nobody has fixed anything. Github hasn't done anything either. They keep referring to where you said to post.
Rain   

    On Tuesday, June 15, 2021, 07:17:11 PM EDT, Martijn Verburg ***@***.***> wrote:  
 
 


@KinFireRain Are you able to submit this issue over at https://bugs.mojang.com/projects/MC/issues/ - the Mojang folks will take the first pass at Triage :-)

**Comment by karianna** [comment]
> I did. I've seen others with similar issues. One of the answers was it's not a bug.Nobody has fixed anything. Github hasn't done anything either. They keep referring to where you said to post. Rain  On Tuesday, June 15, 2021, 07:17:11 PM EDT, Martijn Verburg ***@***.***> wrote: @KinFireRain Are you able to submit this issue over at https://bugs.mojang.com/projects/MC/issues/ - the Mojang folks will take the first pass at Triage :-) — You are receiving this because you were mentioned. Reply to this email directly, view it on GitHub, or unsubscribe.

@KinFireRain Sorry to hear this has been a frustrating experience!  Are you able to share the link to the issue you raised on the Mojang Bug tracker?  I'm happy to follow up and see if I can give more insight.

**Comment by karianna** [comment]
Hi @KinFireRain - How did you get on?  Is there a link to the issue you can post back here?

**Comment by Marcono1234** [comment]
> One of the answers was it's not a bug. Nobody has fixed anything.

For clarification, I ([bug tracker profile link](https://bugs.mojang.com/secure/ViewProfile.jspa?name=marcono1234)) and other Mojang bug tracker volunteers have treated JVM crashes as Invalid until recently and sent users to a community-run technical support, because in the past JVM crashes often occurred due to outdated drivers or other incompatible software being installed; and because it is difficult to reproduce such crashes (without the same hardware). But we have had a discussion with the Mojang developers and they have told us to keep the reports open, so at least for 1.17 we have now also reopened most reports about JVM crashes.

Sorry for the inconvenience this caused for both of you.

Though, assuming @KinFireRain's report is [MC-229182](https://bugs.mojang.com/browse/MC-229182) (since the reporter has the same user name), then that report had not been resolved as Invalid, it was only temporarily resolved as "Awaiting Response" while the reporter had not attached the crash report yet.
Note that there are also other (private) reports about the same crash.
